CREATE ROLE app_user WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'root';


    CREATE DATABASE app
    WITH
    OWNER = app_user
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;