CREATE ROLE swinz_user WITH
    LOGIN
    SUPERUSER
    CREATEDB
    CREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'root';


CREATE DATABASE SWINZ
    WITH
    OWNER = swinz_user
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;